package com.demo.entities;
// Generated Nov 23, 2021, 8:37:11 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * Notifications generated by hbm2java
 */
@Entity
@Table(name = "notifications", catalog = "ecommerce_db")
public class Notifications implements java.io.Serializable {

	private Integer id;
	private Stores stores;
	private Users users;
	private String content;
	
	@JsonFormat(pattern = "dd/MM/yyyy")
	private Date created;
	
	private boolean isRead;
	private boolean isAllUser;
	private boolean isAllStore;

	public Notifications() {
	}

	public Notifications(String content, Date created, boolean isRead, boolean isAllUser, boolean isAllStore) {
		this.content = content;
		this.created = created;
		this.isRead = isRead;
		this.isAllUser = isAllUser;
		this.isAllStore = isAllStore;
	}

	public Notifications(Stores stores, Users users, String content, Date created, boolean isRead, boolean isAllUser,
			boolean isAllStore) {
		this.stores = stores;
		this.users = users;
		this.content = content;
		this.created = created;
		this.isRead = isRead;
		this.isAllUser = isAllUser;
		this.isAllStore = isAllStore;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_id")
	public Stores getStores() {
		return this.stores;
	}

	public void setStores(Stores stores) {
		this.stores = stores;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "content", nullable = false, length = 200)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "is_read", nullable = false)
	public boolean isIsRead() {
		return this.isRead;
	}

	public void setIsRead(boolean isRead) {
		this.isRead = isRead;
	}

	@Column(name = "is_all_user", nullable = false)
	public boolean isIsAllUser() {
		return this.isAllUser;
	}

	public void setIsAllUser(boolean isAllUser) {
		this.isAllUser = isAllUser;
	}

	@Column(name = "is_all_store", nullable = false)
	public boolean isIsAllStore() {
		return this.isAllStore;
	}

	public void setIsAllStore(boolean isAllStore) {
		this.isAllStore = isAllStore;
	}

}
