package com.demo.entities;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Promotions generated by hbm2java
 */
@Entity
@Table(name = "promotions", catalog = "ecommerce_db")
public class Promotions implements java.io.Serializable {

	private Integer id;
	private Date fromDate;
	private Date toDate;
	private boolean applyForAll;
	private double discountPercent;
	private double discountAmount;
	private String productIds;
	private String categoryIds;
	private boolean status;
	private String name;

	public Promotions() {
	}

	public Promotions(Date fromDate, Date toDate, boolean applyForAll, double discountPercent, double discountAmount,
			String productIds, String categoryIds, boolean status, String name) {
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.applyForAll = applyForAll;
		this.discountPercent = discountPercent;
		this.discountAmount = discountAmount;
		this.productIds = productIds;
		this.categoryIds = categoryIds;
		this.status = status;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "from_date", nullable = false, length = 10)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "to_date", nullable = false, length = 10)
	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	@Column(name = "apply_for_all", nullable = false)
	public boolean isApplyForAll() {
		return this.applyForAll;
	}

	public void setApplyForAll(boolean applyForAll) {
		this.applyForAll = applyForAll;
	}

	@Column(name = "discount_percent", nullable = false, precision = 22, scale = 0)
	public double getDiscountPercent() {
		return this.discountPercent;
	}

	public void setDiscountPercent(double discountPercent) {
		this.discountPercent = discountPercent;
	}

	@Column(name = "discount_amount", nullable = false, precision = 22, scale = 0)
	public double getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(double discountAmount) {
		this.discountAmount = discountAmount;
	}

	@Column(name = "product_ids", nullable = false, length = 500)
	public String getProductIds() {
		return this.productIds;
	}

	public void setProductIds(String productIds) {
		this.productIds = productIds;
	}

	@Column(name = "category_ids", nullable = false, length = 500)
	public String getCategoryIds() {
		return this.categoryIds;
	}

	public void setCategoryIds(String categoryIds) {
		this.categoryIds = categoryIds;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
